L2D5A1
scta-texts/kzz7yh pull request #109
Opened 2024-01-27 04:51 UTC by evyryan

2024-02-02 03:57 UTC, RobbieBuhite requested changes

2024-02-02 03:57 UTC, RobbieBuhite commented on kzz7yh-f17284/cod-ve09v2_kzz7yh-f17284.xml
> +                  <lb ed="#V" n="34"/>Contra Ecclu <!-- TODO abbreviation-->. 10 Initium omnis peccati est superbia
```suggestion
                  <lb ed="#V" n="34"/>Contra Eccl. 10 Initium omnis peccati est superbia 
```

2024-02-02 03:57 UTC, RobbieBuhite commented on kzz7yh-f17284/cod-ve09v2_kzz7yh-f17284.xml
> +               <head type="question-title">Utrum peccatum angelorum qui lucifero adheferunt  fuerit superbia vel pusillanimitas</head>
```suggestion
               <head type="question-title">Utrum peccatum angelorum qui lucifero adheserunt fuerit superbia vel pusillanimitas</head>
```

2024-02-02 03:57 UTC, RobbieBuhite commented on kzz7yh-f17284/cod-ve09v2_kzz7yh-f17284.xml
> +      ange<lb ed="#V" n="25" break="no"/>lorum qui lucifero adheferunt <!--TODO: abbreviation? (Question header as well)-->
```suggestion
      ange<lb ed="#V" n="25" break="no"/>lorum qui lucifero adheserunt <!--TODO: Question header-->
```

2024-02-02 03:57 UTC, RobbieBuhite commented on kzz7yh-f17284/cod-ve09v2_kzz7yh-f17284.xml
> +      <lb ed="#V" n="27"/>fuerit pusillanimitas. Quia potius velle subeem <!-- TODO Idk this latin word--> mi
```suggestion
      <lb ed="#V" n="27"/>fuerit pusillanimitas. Quia potius velle subesse
```

2024-02-02 03:57 UTC, RobbieBuhite commented on kzz7yh-f17284/cod-ve09v2_kzz7yh-f17284.xml
> +      <lb ed="#V" n="28"/>nori quam maiori pusillanimitas videtur. Sed angeli qui
```suggestion
      mi<lb ed="#V" n="28" break="no"/>nori quam maiori pusillanimitas videtur. Sed angeli qui 
```

2024-02-02 03:57 UTC, RobbieBuhite commented on kzz7yh-f17284/cod-ve09v2_kzz7yh-f17284.xml
> +                  <lb ed="#V" n="44"/>Contra Hug.i.libro.de sacra. par. . c. 33 <!--TODO abbreviation--> Ex illis qui
```suggestion
                  <lb ed="#V" n="44"/>Contra Hug.i.libro.de sacra. par. 5. c. 33. Ex illis qui 
```

2024-02-02 03:57 UTC, RobbieBuhite commented on kzz7yh-f17284/cod-ve09v2_kzz7yh-f17284.xml
> +      sta<lb ed="#V" n="91" break="no"/>tim cum lucifer peccauit deformatus est: alii autem <!-- TODO: Auteum or aut?-->
```suggestion
      sta<lb ed="#V" n="91" break="no"/>tim cum lucifer peccauit deformatus est: alii autem
```

2024-02-02 03:57 UTC, RobbieBuhite commented on kzz7yh-f17284/cod-ve09v2_kzz7yh-f17284.xml
> +      ter<lb ed="#V" n="109" break="no"/>tia partem stellarum celi et misit eas in terram. Sed
```suggestion
      ter<lb ed="#V" n="109" break="no"/>tiam partem stellarum celi et misit eas in terram. Sed 
```

2024-02-02 03:57 UTC, RobbieBuhite commented on kzz7yh-f17284/cod-ve09v2_kzz7yh-f17284.xml
> +                  <lb ed="#V" n="117"/>Respondeo quod peccatum luciferi non fuit causa propise
```suggestion
                  <lb ed="#V" n="117"/>Respondeo quod peccatum luciferi non fuit causa propositione 
```

2024-02-16 14:43 UTC, jeffreycwitt requested changes
Looking good. Just a few more changes to make.

2024-02-16 14:43 UTC, jeffreycwitt commented on kzz7yh-f17284/cod-ve09v2_kzz7yh-f17284.xml
> +                  <lb ed="#V" n="44"/>Contra Hug.i.libro.de sacra. par. 5. c. 33. Ex illis qui
```suggestion
                  <lb ed="#V" n="44"/>Contra Hug. i. libro de sacra. par. 5. c. 33. Ex illis qui 
```

2024-02-16 14:43 UTC, jeffreycwitt commented on kzz7yh-f17284/cod-ve09v2_kzz7yh-f17284.xml
> +      ange<lb ed="#V" n="25" break="no"/>lorum qui lucifero adheserunt <!--TODO: Question header-->
```suggestion
      ange<lb ed="#V" n="25" break="no"/>lorum qui lucifero adheserunt 
```

2024-02-16 14:43 UTC, jeffreycwitt commented on kzz7yh-f17284/cod-ve09v2_kzz7yh-f17284.xml
> +      ter<lb ed="#V" n="109" break="no"/>tiam partem stellarum celi et misit eas in terram. Sed
```suggestion
                  <lb ed="#V" n="108"/>Contra Apoc. 12. dicitur quod draco cauda sua trahebat 
      ter<lb ed="#V" n="109" break="no"/>tiam partem stellarum celi et misit eas in terram. Sed 
```

2024-02-26 15:21 UTC, jeffreycwitt approved these changes

2024-02-26 15:21 UTC, merged