L2D5A2
scta-texts/kzz7yh pull request #110
Opened 2024-01-27 05:09 UTC by evyryan

2024-02-02 04:18 UTC, RobbieBuhite requested changes

2024-02-02 04:18 UTC, RobbieBuhite commented on kzz7yh-f10183/cod-ve09v2_kzz7yh-f10183.xml
> +               <head type="question-title">Ostendo quod in angelis non sit aliqua realis composito ex esse et essentia</head>
```suggestion
               <head type="question-title">Ostendo quod in angelis non sit aliqua realis compositio ex esse et essentia</head>
```

2024-02-02 04:18 UTC, RobbieBuhite commented on kzz7yh-f18048/cod-ve09v2_kzz7yh-f18048.xml
> +      glo<lb ed="#V" n="80" break="no"/>riam. Et videtur quod non. Quia Magister in praesenti<!-- TODO Abbreviation?!--> dist. ca.
```suggestion
      glo<lb ed="#V" n="80" break="no"/>riam. Et videtur quod non. Quia Magister in praesenti dist. ca. 
```

2024-02-02 04:18 UTC, RobbieBuhite commented on kzz7yh-f18048/cod-ve09v2_kzz7yh-f18048.xml
> +      glo<lb ed="#V" n="80" break="no"/>riam. Et videtur quod non. Quia Magister in praesenti<!-- TODO Abbreviation?!--> dist. ca.
Not sure what you are thinking is an abbreviation?

2024-02-02 04:18 UTC, RobbieBuhite commented on kzz7yh-f18048/cod-ve09v2_kzz7yh-f18048.xml
>        angeli<lb ed="#V" n="131" break="no"/>sint maiores in
```suggestion
      <lb ed="#V" n="131"/>sint maiores in 
```

2024-02-02 04:18 UTC, RobbieBuhite commented on kzz7yh-f18048/cod-ve09v2_kzz7yh-f18048.xml
> +      <lb ed="#V" n="130"/>TErtio queritur vtrum illi
```suggestion
      <lb ed="#V" n="130"/>TErtio queritur vtrum illi angeli
```

2024-02-02 04:18 UTC, RobbieBuhite commented on kzz7yh-f18048/cod-ve09v2_kzz7yh-f18048.xml
> +      <lb ed="#V" n="31"/>fue ita speciale et priuilegiatum dedit
```suggestion
      <lb ed="#V" n="31"/>sue ita speciale et priuilegiatum dedit 
```

2024-02-16 14:45 UTC, jeffreycwitt approved these changes
Looks good!

2024-02-16 14:45 UTC, merged