L2D6A1
scta-texts/kzz7yh pull request #113
Opened 2024-01-27 05:31 UTC by evyryan

2024-02-02 04:41 UTC, RobbieBuhite requested changes

2024-02-02 04:41 UTC, RobbieBuhite commented on kzz7yh-f19041/cod-ve09v2_kzz7yh-f19041.xml
> +      fu<lb ed="#V" n="107" break="no"/>permo <!--TODO: abbreviation?--> ordine non
```suggestion
      <lb ed="#V" n="107"/>primo ordine non 
```

2024-02-02 04:41 UTC, RobbieBuhite commented on kzz7yh-f19041/cod-ve09v2_kzz7yh-f19041.xml
> +      <lb ed="#V" n="6"/>creatus nobilior. Et si stetisset<!--TODO Abbreviation-->: et ad
```suggestion
      <lb ed="#V" n="6"/>creatus nobilior. Et si stetisset: et ad 
```

2024-02-02 04:41 UTC, RobbieBuhite commented on kzz7yh-f19041/cod-ve09v2_kzz7yh-f19041.xml
> +      <lb ed="#V" n="6"/>creatus nobilior. Et si stetisset<!--TODO Abbreviation-->: et ad
I don't think there is an abbreviation after "Stetisset," I think it's just a colon and then the abbreviaiton for "et."

2024-02-02 04:41 UTC, RobbieBuhite commented on kzz7yh-f19041/cod-ve09v2_kzz7yh-f19041.xml
> +               <head type="question-title">Utru de quolibet ordine aliqua multitudo ceciderit</head>
```suggestion
               <head type="question-title">Utrum de quolibet ordine aliqua multitudo ceciderit</head>
```

2024-02-02 04:41 UTC, RobbieBuhite commented on kzz7yh-f19041/cod-ve09v2_kzz7yh-f19041.xml
> +      <lb ed="#V" n="51"/>vetur quod non. Apostolus ad Eph. vltmo.dicit. quod non est
```suggestion
      <lb ed="#V" n="51"/>videtur quod non. Apostolus ad Eph. vltmo.dicit. quod non est 
```

2024-02-16 14:52 UTC, jeffreycwitt approved these changes

2024-02-16 14:52 UTC, merged