L2D7A1
scta-texts/kzz7yh pull request #118
Opened 2024-01-28 21:37 UTC by evyryan

2024-02-03 16:50 UTC, RobbieBuhite requested changes

2024-02-03 16:50 UTC, RobbieBuhite commented on kzz7yh-f21074/cod-ve09v2_kzz7yh-f21074.xml
> +               <head type="question-title">Utrum boni angeli possunt peccare</head>
```suggestion
               <head type="question-title">Utrum boni angeli possint peccare</head>
```

2024-02-03 16:50 UTC, RobbieBuhite commented on kzz7yh-f21074/cod-ve09v2_kzz7yh-f21074.xml
> +                  <lb ed="#V" n="88"/>Contra Aug. i2 de ciuita. cap. 9. Loquens de bonis
```suggestion
                  <lb ed="#V" n="88"/>Contra Aug. 12 de ciuita. cap. 9. Loquens de bonis 
```

2024-02-03 16:50 UTC, RobbieBuhite commented on kzz7yh-f21074/cod-ve09v2_kzz7yh-f21074.xml
> +               <head type="question-title">Utrum liberum arbitrium in bonis angelis sit ita liberum post confirmatione: sicut ante</head>
```suggestion
               <head type="question-title">Utrum liberum arbitrium in bonis angelis sit ita liberum post confirmationem: sicut ante</head>
```

2024-02-16 15:16 UTC, jeffreycwitt approved these changes

2024-02-16 15:16 UTC, merged