L2D7A3
scta-texts/kzz7yh pull request #120
Opened 2024-01-28 22:03 UTC by evyryan

2024-02-03 17:44 UTC, RobbieBuhite requested changes

2024-02-03 17:44 UTC, RobbieBuhite commented on kzz7yh-f22165/cod-ve09v2_kzz7yh-f22165.xml
> +                  <lb ed="#V" n="99"/>Respondeo d obliuio potest accipi. Uel
```suggestion
                  <lb ed="#V" n="99"/>Respondeo quod obliuio potest accipi. Uel 
```

2024-02-03 17:44 UTC, RobbieBuhite commented on kzz7yh-f22165/cod-ve09v2_kzz7yh-f22165.xml
> +               <head type="question-title">Utrum tempestatum et pluuiarum et aliarum</head>
```suggestion
               <head type="question-title">Utrum tempestatum et pluuiarum et aliarum impressionum naturalium futurarum sit in eis vel esse possit per eorum naturalem virtutem certa precognitio</head>
```

2024-02-03 17:44 UTC, RobbieBuhite commented on kzz7yh-f22165/cod-ve09v2_kzz7yh-f22165.xml
> +      precogno<lb ed="#V" n="49" break="no"/>scendo talia: quam sensitiua quoruncumque <!--TODO: abbreviation?--> brutorum
```suggestion
      precogno<lb ed="#V" n="49" break="no"/>scendo talia: quam sensitiua quorumcumque brutorum 
```

2024-02-16 15:17 UTC, jeffreycwitt approved these changes

2024-02-16 15:17 UTC, merged