Keep going
scta-texts/kzz7yh pull request #123
Opened 2024-01-29 17:05 UTC by evyryan

still working ont his test

2024-02-01 21:37 UTC, evyryan commented
I committed my changes, and this is finished. Not sure how to change the title

2024-02-03 18:20 UTC, RobbieBuhite requested changes

2024-02-03 18:20 UTC, RobbieBuhite commented on kzz7yh-f24075/cod-ve09v2_kzz7yh-f24075.xml
> +      <lb ed="#V" n="10"/>quod demones sunt aerei<!--word?-->. Et. xi. lib. 22. cap. quod
```suggestion
      <lb ed="#V" n="10"/>quod demones sunt aerei. Et. xi. lib. 22. cap. quod 
```

2024-02-03 18:20 UTC, RobbieBuhite commented on kzz7yh-f24075/cod-ve09v2_kzz7yh-f24075.xml
> +      <lb ed="#V" n="10"/>quod demones sunt aerei<!--word?-->. Et. xi. lib. 22. cap. quod
Yes, "aereus, -a, -um," the adjective meaning "bronze," from "aes, aeris," f., "bronze."

2024-02-03 18:20 UTC, RobbieBuhite commented on kzz7yh-f24075/cod-ve09v2_kzz7yh-f24075.xml
> +      <lb ed="#V" n="65"/>virtbus<!--word--> animalibus sunt he proprietates scilicet vt audiat verbum
```suggestion
      <lb ed="#V" n="65"/>virtutibus animalibus sunt he proprietates scilicet vt audiat verbum 
```

2024-02-03 18:20 UTC, RobbieBuhite commented on kzz7yh-f24075/cod-ve09v2_kzz7yh-f24075.xml
> +      <lb ed="#V" n="103"/>Gensem. <!-- or Genesis?--> 18. dicit de angelis qui apparuerunt
```suggestion
      <lb ed="#V" n="103"/>Genesem. 18. dicit de angelis qui apparuerunt 
```

2024-02-03 18:20 UTC, RobbieBuhite commented on kzz7yh-f24075/cod-ve09v2_kzz7yh-f24075.xml
> +      <lb ed="#V" n="123"/>potuisset hospitio suscipere<!-- abbreviation-->: et cibos
```suggestion
      <lb ed="#V" n="123"/>potuisset hospitio suscipere: et cibos 
```

2024-02-03 18:20 UTC, RobbieBuhite commented on kzz7yh-f24075/cod-ve09v2_kzz7yh-f24075.xml
> +      <lb ed="#V" n="123"/>potuisset hospitio suscipere<!-- abbreviation-->: et cibos
It's just a colon for punctuation followed by the abbrev. for "et."

2024-02-03 18:20 UTC, RobbieBuhite commented on kzz7yh-f24075/cod-ve09v2_kzz7yh-f24075.xml
> +      <lb ed="#V" n="13"/>vocat celeste elementum aerem. An
```suggestion
      <lb ed="#V" n="13"/>vocat celeste elementum aerem. In
```

2024-02-03 18:20 UTC, RobbieBuhite commented on kzz7yh-f24075/cod-ve09v2_kzz7yh-f24075.xml
> +               <head type="question-title">Utrum corpora quae demones assumunt sint perfectibilia ab animal intellectiva<!--endings--></head>
```suggestion
               <head type="question-title">Utrum corpora quae demones assumunt sint perfectibilia a animal intellectiva<!--endings--></head>
```

2024-02-03 18:20 UTC, RobbieBuhite commented on kzz7yh-f24075/cod-ve09v2_kzz7yh-f24075.xml
> +      intel<lb ed="#V" n="45" break="no"/>llectiua<!--ending?-->. Et videtur quod sic. Quia vt habitum est
```suggestion
      intel<lb ed="#V" n="45" break="no"/>llectiua. Et videtur quod sic. Quia vt habitum est 
```

2024-02-03 18:20 UTC, RobbieBuhite commented on kzz7yh-f24075/cod-ve09v2_kzz7yh-f24075.xml
> +      intel<lb ed="#V" n="45" break="no"/>llectiua<!--ending?-->. Et videtur quod sic. Quia vt habitum est
It's 1st dec. ablative, singular, feminine matching with "anima" after the preposition "ab."

2024-02-03 18:20 UTC, RobbieBuhite commented on kzz7yh-f24075/cod-ve09v2_kzz7yh-f24075.xml
> +                  <lb ed="#V" n="34"/>Contra Glo. Genm.<!--abbreviation--> 6. super illud videntes filii dei filias
```suggestion
                  <lb ed="#V" n="34"/>Contra Glo. Genesis 6. super illud videntes filii dei filias 
```

2024-02-16 15:23 UTC, jeffreycwitt requested changes

2024-02-16 15:23 UTC, jeffreycwitt commented on kzz7yh-f24075/cod-ve09v2_kzz7yh-f24075.xml
> +                  <lb ed="#V" n="12"/>Ad primum in oppositum dicendum: quo illa Glosu.<!-- abbreviation-->
```suggestion
                  <lb ed="#V" n="12"/>Ad primum in oppositum dicendum: quo illa Glossa
```

2024-02-16 15:23 UTC, jeffreycwitt commented on kzz7yh-f24075/cod-ve09v2_kzz7yh-f24075.xml
> +               <head type="question-title">Utrum corpora quae demones assumunt sint perfectibilia a animal intellectiva<!--endings--></head>
```suggestion
               <head type="question-title">Utrum corpora quae daemones assumunt sint perfectibilia a anima intellectiva</head>
```

2024-02-16 15:23 UTC, jeffreycwitt commented on kzz7yh-f24075/cod-ve09v2_kzz7yh-f24075.xml
> +            <!--Left off here-->
```suggestion
```

2024-02-16 15:23 UTC, jeffreycwitt commented on kzz7yh-f24075/cod-ve09v2_kzz7yh-f24075.xml
> +               <head type="question-title">Utrum in illis corporibus assumptis possint demones exercere actus virtutis nutritive <!--word?--></head>
```suggestion
               <head type="question-title">Utrum in illis corporibus assumptis possint daemones exercere actus virtutis nutritive</head>
```

2024-02-26 15:22 UTC, jeffreycwitt approved these changes

2024-02-26 15:22 UTC, merged