L2D8A2
scta-texts/kzz7yh pull request #125
Opened 2024-02-02 18:38 UTC by evyryan

Something happened to Quaestio 6 section. Other than that, question headers added. Fatheads finished. Some abbreviation questions.

2024-02-10 00:16 UTC, RobbieBuhite requested changes

2024-02-10 00:16 UTC, RobbieBuhite commented on kzz7yh-f25054/cod-ve09v2_kzz7yh-f25054.xml
> +      inti<lb ed="#V" n="82" break="no"/>mare humanis corporibus. Glosilnus <!-- Abbreviation--> super illud
```suggestion
      inti<lb ed="#V" n="82" break="no"/>mare humanis corporibus. Glosilinus super illud 
```

2024-02-10 00:16 UTC, RobbieBuhite commented on kzz7yh-f25054/cod-ve09v2_kzz7yh-f25054.xml
> +                  <lb ed="#V" n="78"/>Contra Aug. i8 de ciui cap. i7 refert <!--Abbreviation name here-->
```suggestion
                  <lb ed="#V" n="78"/>Contra Aug. i8 de ciui cap. 17 refert Uarronem
```

2024-02-10 00:16 UTC, RobbieBuhite commented on kzz7yh-f25054/cod-ve09v2_kzz7yh-f25054.xml
> +      co<lb ed="#V" n="95" break="no"/>guoscere. Et videtur quod sic. Refert tullius. i.
```suggestion
      <sic>co<lb ed="#V" n="95" break="no"/>guoscere</sic>. Et videtur quod sic. Refert tullius. i. 
```

2024-02-16 15:26 UTC, jeffreycwitt requested changes

2024-02-26 15:25 UTC, jeffreycwitt approved these changes

2024-02-26 15:25 UTC, merged