L2D15A2
scta-texts/kzz7yh pull request #154
Opened 2024-02-16 16:47 UTC by evyryan

Added Question headers
fixed fatheads
paragraph error

2024-02-24 01:41 UTC, RobbieBuhite requested changes

2024-02-24 01:41 UTC, RobbieBuhite commented on kzz7yh-f45810/cod-ve09v2_kzz7yh-f45810.xml
> +      <lb ed="#V" n="70"/>non optet ponere aliquid in materia
```suggestion
      <lb ed="#V" n="70"/>non oportet ponere aliquid in materia 
```

2024-02-26 15:20 UTC, jeffreycwitt requested changes

2024-02-26 15:20 UTC, jeffreycwitt commented on kzz7yh-f45810/cod-ve09v2_kzz7yh-f45810.xml
> +               <head type="question-title">Utrum anime brutorum sint extense</head>
```suggestion
               <head type="question-title">Utrum animae brutorum sint extense</head>
```

2024-02-26 15:20 UTC, jeffreycwitt commented on kzz7yh-f45810/cod-ve09v2_kzz7yh-f45810.xml
> +                  <lb ed="#V" n="95"/>Ad istam quonem dicunt aliqui quod ante
```suggestion
                  <lb ed="#V" n="95"/>Ad istam quaestionem dicunt aliqui quod ante 
```

2024-02-26 15:20 UTC, jeffreycwitt commented on kzz7yh-f45810/cod-ve09v2_kzz7yh-f45810.xml
>        per<lb ed="#V" n="97" break="no"/>se: sed per extensionem materie innitentes experientie in
```suggestion
      bru<lb ed="#V" n="96" break="no"/>torum sunt extense: non per
      <lb ed="#V" n="97"/>se: sed per extensionem materie innitentes experientie in 
```

2024-03-18 14:24 UTC, jeffreycwitt approved these changes

2024-03-18 14:25 UTC, merged