L2D15A3
scta-texts/kzz7yh pull request #158
Opened 2024-02-16 18:09 UTC by evyryan

Added question headers.
Fixed fatheads.

2024-02-19 16:37 UTC, jeffreycwitt requested changes

2024-02-19 16:37 UTC, jeffreycwitt commented on kzz7yh-f46637/cod-ve09v2_kzz7yh-f46637.xml
> +                  <lb ed="#V" n="83"/>Contra secundum philosophum. 5 metapiheum<!--abbreviation-->. Accidens est prius
```suggestion
                  <lb ed="#V" n="83"/>Contra secundum <ref>philosophum. 5 metaph.</ref> Accidens est prius 
```

2024-02-19 16:37 UTC, jeffreycwitt commented on kzz7yh-f46637/cod-ve09v2_kzz7yh-f46637.xml
> +      <lb ed="#V" n="28"/>quod sic Commen. in expositione verbi Arum. 7. meta. Si
```suggestion
      <lb ed="#V" n="28"/>quod sic <ref>Commentator in expositione verbi Aristotelis. 7. metaphysicae</ref>. Si
```

2024-02-19 16:37 UTC, jeffreycwitt commented on kzz7yh-f46637/cod-ve09v2_kzz7yh-f46637.xml
> +                  <lb ed="#V" n="90"/>Ad primum n<!--n?--> oppositum dicendum: quod
```suggestion
                  <lb ed="#V" n="90"/>Ad primum <unclear>in<!-- "i" looks smudged away</unclear> oppositum dicendum: quod 
```

2024-02-20 23:01 UTC, evyryan commented
Why does this have an X by it???

2024-02-20 23:01 UTC, evyryan commented
> Why does this have an X by it???

@jeffreycwitt

2024-03-18 14:29 UTC, jeffreycwitt approved these changes

2024-03-18 14:29 UTC, merged