L2D16A1
scta-texts/kzz7yh pull request #170
Opened 2024-02-23 20:13 UTC by evyryan

Added question headers
Fixed fatheads
added references
First question is formatted oddly in the text. Not sure.

2024-02-24 02:16 UTC, RobbieBuhite requested changes

2024-02-24 02:16 UTC, RobbieBuhite commented on kzz7yh-f48103/cod-ve09v2_kzz7yh-f48103.xml
> +      ima<lb ed="#V" n="30" break="no"/>ginem: secet <!--word?--> quando est imago in formis: sicut cum in ligno
```suggestion
      ima<lb ed="#V" n="30" break="no"/>ginem: secundum quando est imago in formis: sicut cum in ligno
```

2024-02-24 02:16 UTC, RobbieBuhite commented on kzz7yh-f48103/cod-ve09v2_kzz7yh-f48103.xml
> +               <head type="question-title">Utrum imago dei its expresse sit in homine sicut in angelo</head>
```suggestion
               <head type="question-title">Utrum imago dei ita expresse sit in homine sicut in angelo</head>
```

2024-03-29 15:59 UTC, jeffreycwitt approved these changes

2024-03-29 15:59 UTC, merged