L2D20A2
scta-texts/kzz7yh pull request #203
Opened 2024-03-07 02:54 UTC by evyryan

fixed fatheads
added question headers
some formatting changes

2024-03-14 03:18 UTC, RobbieBuhite requested changes

2024-03-14 03:18 UTC, RobbieBuhite commented on kzz7yh-f58876/cod-ve09v2_kzz7yh-f58876.xml
> +               <head type="question-title">Utrum pueri statem cum nati fuissent habuissent perfectum membrorum virsum</head>
```suggestion
               <head type="question-title">Utrum pueri statim cum nati fuissent habuissent perfectum membrorum usum</head>
```

2024-03-14 03:18 UTC, RobbieBuhite commented on kzz7yh-f58876/cod-ve09v2_kzz7yh-f58876.xml
> +      Quaestio II <!--Word "vsum" I am confused about, occurs several times in this paragraph-->
```suggestion
      Quaestio II 
```

2024-03-14 03:18 UTC, RobbieBuhite commented on kzz7yh-f58876/cod-ve09v2_kzz7yh-f58876.xml
> +      Quaestio II <!--Word "vsum" I am confused about, occurs several times in this paragraph-->
The word is "usum," as in "use" as a noun.

2024-03-14 03:18 UTC, RobbieBuhite commented on kzz7yh-f58876/cod-ve09v2_kzz7yh-f58876.xml
> +      <lb ed="#V" n="100"/>membrorum virsum: et videtur quod sic. quaedam animalia statim
```suggestion
      <lb ed="#V" n="100"/>membrorum vsum: et videtur quod sic. quaedam animalia statim 
```

2024-03-14 03:18 UTC, RobbieBuhite commented on kzz7yh-f58876/cod-ve09v2_kzz7yh-f58876.xml
> +      <lb ed="#V" n="101"/>cum nascunt habent sufficientem membrorum virsum: ergo cum homo
```suggestion
      <lb ed="#V" n="101"/>cum nascunt habent sufficientem membrorum vsum: ergo cum homo
```

2024-03-14 03:18 UTC, RobbieBuhite commented on kzz7yh-f58876/cod-ve09v2_kzz7yh-f58876.xml
> +      nasce<lb ed="#V" n="103" break="no"/>retur non tantum sufficientem: sed persfactum membrorum virsum haberet.
```suggestion
      nasce<lb ed="#V" n="103" break="no"/>retur non tantum sufficientem: sed persfactum membrorum vsum haberet.
```

2024-03-14 03:18 UTC, RobbieBuhite commented on kzz7yh-f58876/cod-ve09v2_kzz7yh-f58876.xml
> +      per<lb ed="#V" n="114" break="no"/>fectione organorum. Sed in statu innocente filii non
```suggestion
      per<lb ed="#V" n="114" break="no"/>fectione organorum. Sed in statu innocentie filii non 
```

2024-03-14 03:18 UTC, RobbieBuhite commented on kzz7yh-f58876/cod-ve09v2_kzz7yh-f58876.xml
> +      ge<lb ed="#V" n="28" break="no"/>nerarentur: conseqens est oino<!--word--> quod est sine peccato nascerentur: ergo
```suggestion
      ge<lb ed="#V" n="28" break="no"/>nerarentur: consequens est omnino quod est sine peccato nascerentur: ergo 
```

2024-03-14 03:18 UTC, RobbieBuhite commented on kzz7yh-f58876/cod-ve09v2_kzz7yh-f58876.xml
> +      <lb ed="#V" n="103"/>ad virsum nec quantum ad habitum: sed in processu temporis
```suggestion
      <lb ed="#V" n="103"/>ad vsum nec quantum ad habitum: sed in processu temporis 
```

2024-03-14 03:18 UTC, RobbieBuhite commented on kzz7yh-f58876/cod-ve09v2_kzz7yh-f58876.xml
> +                  <lb ed="#V" n="125"/>Ad primum in opositum cum dicitur: quod ignorantia peciea<!--word--> est etc.
```suggestion
                  <lb ed="#V" n="125"/>Ad primum in opositum cum dicitur: quod ignorantia pena est etc. 
```

2024-03-14 03:18 UTC, RobbieBuhite commented on kzz7yh-f58876/cod-ve09v2_kzz7yh-f58876.xml
> +      ingran<lb ed="#V" n="127" break="no"/>tia: sed secundum hug id est li. de sacr. per. 6 c. 26 non omnis qui aliquid nescit aut
```suggestion
      ingran<lb ed="#V" n="127" break="no"/>tia: sed secundum <ref>hug id est li. de sacr. per. 6 c. 26</ref> non omnis qui aliquid nescit aut 
```

2024-03-14 03:18 UTC, RobbieBuhite commented on kzz7yh-f58876/cod-ve09v2_kzz7yh-f58876.xml
> +      <lb ed="#V" n="12"/>est pro statu naturae lapse et de lege communi.
```suggestion
      <lb ed="#V" n="12"/>est pro statu nature lapse et de lege communi. 
```

2024-04-06 23:54 UTC, jeffreycwitt approved these changes

2024-04-06 23:54 UTC, merged