L2D21A2
scta-texts/kzz7yh pull request #208
Opened 2024-03-08 02:45 UTC by evyryan

fixed fatheads
added question headers, one question i am unsure of

2024-03-14 03:28 UTC, RobbieBuhite requested changes

2024-03-14 03:28 UTC, RobbieBuhite commented on kzz7yh-f60895/cod-ve09v2_kzz7yh-f60895.xml
>        effecti<lb ed="#V" n="120" break="no"/>bus sequentibus est. Ergo prima superbia que fuitil
```suggestion
      effecti<lb ed="#V" n="120" break="no"/>bus sequentibus est. Ergo prima superbia que fuit
```

2024-03-14 03:28 UTC, RobbieBuhite commented on kzz7yh-f60895/cod-ve09v2_kzz7yh-f60895.xml
> +               <head type="question-title">Utrum temptationi que est a carne vel illi que est ab hoste</head>
```suggestion
               <head type="question-title">Utrum cui istarum temptationum difficilius sit resistere</head>
```

2024-03-14 03:28 UTC, RobbieBuhite commented on kzz7yh-f60895/cod-ve09v2_kzz7yh-f60895.xml
> +               <!--check question header-->
```suggestion
```

2024-04-08 14:09 UTC, jeffreycwitt approved these changes

2024-04-08 14:09 UTC, merged