L2D22CL
scta-texts/kzz7yh pull request #221
Opened 2024-03-14 20:02 UTC by evyryan

Two abbreviations I am unsure of

2024-03-22 12:06 UTC, RobbieBuhite requested changes

2024-03-22 12:06 UTC, RobbieBuhite commented on kzz7yh-f64843/cod-ve09v2_kzz7yh-f64843.xml
>        <lb ed="#V" n="114"/>dinem dei cum
```suggestion
      similitu<lb ed="#V" n="114" break="no"/>dinem dei cum 
```

2024-03-22 12:06 UTC, RobbieBuhite commented on kzz7yh-f64843/cod-ve09v2_kzz7yh-f64843.xml
>                 <lb ed="#V" n="113"/>CIrca litteram voluit here silitum
```suggestion
               <lb ed="#V" n="113"/>CIrca litteram voluit habere  
```

2024-03-22 12:06 UTC, RobbieBuhite commented on kzz7yh-f64843/cod-ve09v2_kzz7yh-f64843.xml
> +      crea<lb ed="#V" n="117" break="no"/>tura cogitari non potest: ergo mulier non potuit appetem deo equari<!--word-->.
```suggestion
      crea<lb ed="#V" n="117" break="no"/>tura cogitari non potest: ergo mulier non potuit appetere deo equari<!--word-->. 
```

2024-03-22 12:06 UTC, RobbieBuhite commented on kzz7yh-f64843/cod-ve09v2_kzz7yh-f64843.xml
> +      crea<lb ed="#V" n="117" break="no"/>tura cogitari non potest: ergo mulier non potuit appetem deo equari<!--word-->.
Also unsure of this word

2024-03-22 12:06 UTC, RobbieBuhite commented on kzz7yh-f64843/cod-ve09v2_kzz7yh-f64843.xml
> +               <lb ed="#V" n="118"/>¶ Rmnens<!--word--> quod sicut potest cogitari ita appeti: cogitari potest secundum
```suggestion
               <lb ed="#V" n="118"/>¶ Respondeo quod sicut potest cogitari ita appeti: cogitari potest secundum 
```

2024-04-08 14:30 UTC, jeffreycwitt commented on kzz7yh-f64843/cod-ve09v2_kzz7yh-f64843.xml
> +      crea<lb ed="#V" n="117" break="no"/>tura cogitari non potest: ergo mulier non potuit appetere deo equari<!--word-->.
```suggestion
      crea<lb ed="#V" n="117" break="no"/>tura cogitari non potest: ergo mulier non potuit appetere deo equari. 
```

2024-04-08 14:30 UTC, jeffreycwitt approved these changes

2024-04-08 14:30 UTC, merged