L2D23A1
scta-texts/kzz7yh pull request #224
Opened 2024-03-15 16:10 UTC by evyryan

one line coord error
fixed fatheads
added question headers

2024-03-22 12:25 UTC, RobbieBuhite requested changes

2024-03-22 12:25 UTC, RobbieBuhite commented on kzz7yh-f65243/cod-ve09v2_kzz7yh-f65243.xml
> +      <lb ed="#V" n="28"/>virtutem quae alicui creatur est supernatural: posset deus alicui
```suggestion
      <lb ed="#V" n="28"/>virtutem quae alicui creatura est supernaturalis: posset deus alicui 
```

2024-03-22 12:25 UTC, RobbieBuhite commented on kzz7yh-f65243/cod-ve09v2_kzz7yh-f65243.xml
> +      <lb ed="#V" n="29"/>alii creature facennalem<!--Something going on here-->: sed per virtutem supernaturalem vt per glutiam
```suggestion
      <lb ed="#V" n="29"/>alii creature facere natalem: sed per virtutem supernaturalem vt per glutiam 
```

2024-03-22 12:25 UTC, RobbieBuhite commented on kzz7yh-f65243/cod-ve09v2_kzz7yh-f65243.xml
> +      <lb ed="#V" n="41"/>facem creaturam rationalem vel<!--abbreviation--> intellectualem qui naturaliter non posset
```suggestion
      <lb ed="#V" n="41"/>facem creaturam rationalem vel intellectualem qui naturaliter non posset 
```

2024-03-22 12:25 UTC, RobbieBuhite commented on kzz7yh-f65243/cod-ve09v2_kzz7yh-f65243.xml
> +      crea<lb ed="#V" n="49" break="no"/>tura rationalis vniversal intellectualis naturaliter carens libera voluntate:
```suggestion
      crea<lb ed="#V" n="49" break="no"/>tura rationalis vel intellectualis naturaliter carens libera voluntate: 
```

2024-03-22 12:25 UTC, RobbieBuhite commented on kzz7yh-f65243/cod-ve09v2_kzz7yh-f65243.xml
> +      <lb ed="#V" n="82"/><ref>Eccls 31.</ref> Quod potuit transgredi et non transgressus est: ergo melius est
```suggestion
      <lb ed="#V" n="82"/><ref>Eccles 31.</ref> Quod potuit transgredi et non transgressus est: ergo melius est 
```

2024-03-22 12:25 UTC, RobbieBuhite commented on kzz7yh-f65243/cod-ve09v2_kzz7yh-f65243.xml
> +                  <lb ed="#V" n="69"/>culosum: et sicut dicitur <ref>Ecclsi. 3.</ref> Qui amat periculum
```suggestion
                  <lb ed="#V" n="69"/>culosum: et sicut dicitur <ref>Ecclesi. 3.</ref> Qui amat periculum 
```

2024-04-08 14:37 UTC, jeffreycwitt commented on kzz7yh-f65243/cod-ve09v2_kzz7yh-f65243.xml
>        <!--00197.xml-->
```suggestion
      <lb ed="#V" n="136"/>superandum. Sed deus sciebat hominem esse a diabolo per illam 
      <!--00197.xml-->
```

2024-04-08 14:38 UTC, jeffreycwitt approved these changes

2024-04-08 14:38 UTC, merged