L2D23A2
scta-texts/kzz7yh pull request #225
Opened 2024-03-15 17:05 UTC by evyryan

Fixed fatheads
added question headers

2024-03-22 12:32 UTC, RobbieBuhite requested changes

2024-03-22 12:32 UTC, RobbieBuhite commented on kzz7yh-f65956/cod-ve09v2_kzz7yh-f65956.xml
> +               <lb ed="#V" n="131"/>COnsequenter queritur de 20 principali
```suggestion
               <lb ed="#V" n="131"/>COnsequenter queritur de 2o principali
```

2024-03-22 12:32 UTC, RobbieBuhite commented on kzz7yh-f65956/cod-ve09v2_kzz7yh-f65956.xml
> +      <lb ed="#V" n="92" break="no"/>statu innocentie dicit quod cognouit homo creatorem suum
```suggestion
      <lb ed="#V" n="92"/>statu innocentie dicit quod cognouit homo creatorem suum 
```

2024-03-22 12:32 UTC, RobbieBuhite commented on kzz7yh-f65956/cod-ve09v2_kzz7yh-f65956.xml
> +                  <lb ed="#V" n="104"/>Contra ad <ref>Hebrews. xi.</ref> sine fide impossibile est quemquam
```suggestion
                  <lb ed="#V" n="104"/>Contra ad <ref>Hebreos. xi.</ref> sine fide impossibile est quemquam 
```

2024-03-22 12:32 UTC, RobbieBuhite commented on kzz7yh-f65956/cod-ve09v2_kzz7yh-f65956.xml
> +      <lb ed="#V" n="80" break="no"/>hominis: sed pena damnati.
```suggestion
      <lb ed="#V" n="80"/>hominis: sed pena damnati.
```

2024-03-22 12:32 UTC, RobbieBuhite commented on kzz7yh-f65956/cod-ve09v2_kzz7yh-f65956.xml
>        ¶ Item Aug. in Ench. cap. 9.
```suggestion
      ¶ Item <ref>Aug. in Ench. cap. 9.</ref> 
```

2024-04-08 14:39 UTC, jeffreycwitt approved these changes

2024-04-08 14:39 UTC, merged