l3d4a1
scta-texts/kzz7yh pull request #230
Opened 2024-03-19 01:37 UTC by Menc1us

finished

2024-03-22 12:50 UTC, RobbieBuhite requested changes

2024-03-22 12:50 UTC, RobbieBuhite commented on kzz7yh-g08618/cod-ve09v3_kzz7yh-g08618.xml
> +                  <lb ed="#V" n="43"/>Contra. <ref>Math. 1. Quod</ref> in ea natum est de spiritu
```suggestion
                  <lb ed="#V" n="43"/>Contra. <ref>Math. 1.</ref> Quod in ea natum est de spiritu 
```

2024-03-22 12:50 UTC, RobbieBuhite commented on kzz7yh-g08618/cod-ve09v3_kzz7yh-g08618.xml
> +      efi<lb ed="#V" n="48" break="no"/>cienti: quia operatio illi persone appropriatur cuius
```suggestion
      effi<lb ed="#V" n="48" break="no"/>cienti: quia operatio illi persone appropriatur cuius 
```

2024-03-22 12:50 UTC, RobbieBuhite commented on kzz7yh-g08618/cod-ve09v3_kzz7yh-g08618.xml
> +        <lb ed="#V" n="106"/>Contra. <ref>August. 2. libro de trinitate cap. 10 </ref>dicit quod
```suggestion
        <lb ed="#V" n="106"/>Contra. <ref>August. 2. libro de trinitate cap. 10.</ref> dicit quod 
```

2024-04-22 15:04 UTC, jeffreycwitt commented on kzz7yh-g08618/cod-ve09v3_kzz7yh-g08618.xml
> +      effi<lb ed="#V" n="48" break="no"/>cienti: quia operatio illi persone appropriatur cuius
```suggestion
      <sic>ef<lb ed="#V" n="48" break="no"/>cienti</sic>: quia operatio illi persone appropriatur cuius 
```

2024-04-22 15:04 UTC, merged