L3d4a2
scta-texts/kzz7yh pull request #231
Opened 2024-03-20 01:29 UTC by Menc1us

finished

2024-03-22 12:54 UTC, RobbieBuhite requested changes

2024-03-22 12:54 UTC, RobbieBuhite commented on kzz7yh-g08970/cod-ve09v3_kzz7yh-g08970.xml
> +               <head type="question-title">Utrum eata virgo vere dici possit mater dei.</head>
```suggestion
               <head type="question-title">Utrum beata virgo vere dici possit mater dei.</head>
```

2024-03-22 12:54 UTC, RobbieBuhite commented on kzz7yh-g08970/cod-ve09v3_kzz7yh-g08970.xml
> +                  <lb ed="#V" n="75"/>Contra. <ref>Damas. lib. 3. c. 12 </ref> theotochos est dei
```suggestion
                  <lb ed="#V" n="75"/>Contra. <ref>Damas. lib. 3. c. 12.</ref> theotochos est dei 
```

2024-04-22 15:07 UTC, jeffreycwitt commented on kzz7yh-g08970/cod-ve09v3_kzz7yh-g08970.xml
>        mate<lb ed="#V" n="47" break="no"/>riam: sed etiam per virtutem generatiuam: materiam
```suggestion
                  <lb ed="#V" n="46"/>Ad primum in oppositum dicendum:quod beata 
                  vir<!--TODO line break here-->go non tantum ministrauit 
                  mate<lb ed="#V" n="47" break="no"/>riam: sed etiam per virtutem generatiuam: materiam 
```

2024-04-22 15:07 UTC, jeffreycwitt commented on kzz7yh-g08970/cod-ve09v3_kzz7yh-g08970.xml
> +      <lb ed="#V" n="65"/>SEecundo queritur vtrum beata virgo
```suggestion
      <lb ed="#V" n="65"/>SEcundo queritur vtrum beata virgo 
```

2024-04-22 15:08 UTC, jeffreycwitt approved these changes

2024-04-22 15:08 UTC, merged