l3d5a1
scta-texts/kzz7yh pull request #235
Opened 2024-03-21 19:18 UTC by Menc1us

finished

2024-03-22 13:02 UTC, RobbieBuhite requested changes

2024-03-22 13:02 UTC, RobbieBuhite commented on kzz7yh-g10450/cod-ve09v3_kzz7yh-g10450.xml
> +                  <lb ed="#V" n="89"/>Contra. Damas. eodem libro et eodem. c. quoniam deitas unita
```suggestion
                  <lb ed="#V" n="89"/>Contra. <ref>Damas. eodem libro et eodem. c.</ref> quoniam deitas unita
```

2024-03-22 13:02 UTC, RobbieBuhite commented on kzz7yh-g10450/cod-ve09v3_kzz7yh-g10450.xml
> +                  <lb ed="#V" n="95"/>Respondeo quod assumere tripliter potest dici scilicet comuniter
```suggestion
                  <lb ed="#V" n="95"/>Respondeo quod assumere tripliciter potest dici scilicet communiter 
```

2024-03-22 13:02 UTC, RobbieBuhite commented on kzz7yh-g10450/cod-ve09v3_kzz7yh-g10450.xml
> +      <lb ed="#V" n="108"/>quia deitas magis signat illud quod signat in abstractione: quoniam
```suggestion
      <lb ed="#V" n="108"/>quia deitas magis signat illud quod significat in abstractione: quoniam 
```

2024-03-22 13:02 UTC, RobbieBuhite commented on kzz7yh-g10450/cod-ve09v3_kzz7yh-g10450.xml
> +      <lb ed="#V" n="109"/>diuina natura: vnde non ita signat rem suam vt principium
```suggestion
      <lb ed="#V" n="109"/>diuina natura: vnde non ita significat rem suam vt principium 
```

2024-04-08 14:56 UTC, jeffreycwitt approved these changes

2024-04-08 14:56 UTC, merged