L2D24A2
scta-texts/kzz7yh pull request #239
Opened 2024-03-23 00:54 UTC by evyryan

Fixed fatheads
added question headers

2024-03-30 13:30 UTC, RobbieBuhite requested changes

2024-03-30 13:30 UTC, RobbieBuhite commented on kzz7yh-f69560/cod-ve09v2_kzz7yh-f69560.xml
> +      <lb ed="#V" n="120"/>distictio intellectus in
```suggestion
      <lb ed="#V" n="120"/>distinctio intellectus in 
```

2024-03-30 13:30 UTC, RobbieBuhite commented on kzz7yh-f69560/cod-ve09v2_kzz7yh-f69560.xml
> +      passio<lb ed="#V" n="79" break="no"/>nes animales que sunt in appetitu sensitiuo: ergo videtur<!--not sure if tur symbol or ink smudge-->
```suggestion
      passio<lb ed="#V" n="79" break="no"/>nes animales que sunt in appetitu sensitiuo: ergo videtur
```

2024-03-30 13:30 UTC, RobbieBuhite commented on kzz7yh-f69560/cod-ve09v2_kzz7yh-f69560.xml
>        disti<lb ed="#V" n="125" break="no"/>cte persone: ita videtur quod in isto coniugio spirituali portio superior et in
```suggestion
      distin<lb ed="#V" n="125" break="no"/>cte persone: ita videtur quod in isto coniugio spirituali portio superior et in 
```

2024-03-30 13:30 UTC, RobbieBuhite commented on kzz7yh-f69560/cod-ve09v2_kzz7yh-f69560.xml
> +      commemora<lb ed="#V" n="14" break="no"/>ui id est in superiorem portionem et inferiorem nisi per
```suggestion
      commemora<lb ed="#V" n="14" break="no"/>ui id est in superiorem portionem et inferiorem nisi per officia
```

2024-03-30 13:30 UTC, RobbieBuhite commented on kzz7yh-f69560/cod-ve09v2_kzz7yh-f69560.xml
>        officia<lb ed="#V" n="15" break="no"/>geminamus: ergo non sunt due potentie.
```suggestion
      <lb ed="#V" n="15"/>geminamus: ergo non sunt due potentie.
```

2024-04-22 15:15 UTC, jeffreycwitt approved these changes

2024-04-22 15:15 UTC, merged