L2D24A3
scta-texts/kzz7yh pull request #241
Opened 2024-03-23 19:12 UTC by evyryan

Fixed fatheads
added question headers
one paragraph needs to be added

2024-03-30 13:49 UTC, RobbieBuhite requested changes

2024-03-30 13:49 UTC, RobbieBuhite commented on kzz7yh-f70880/cod-ve09v2_kzz7yh-f70880.xml
> +                  <lb ed="#V" n="26"/>Contra prius ordine nature est conuersio itellecius <!--should have t?-->
```suggestion
                  <lb ed="#V" n="26"/>Contra prius ordine nature est conuersio <sic>intellecius</sic>

2024-03-30 13:49 UTC, RobbieBuhite commented on kzz7yh-f70880/cod-ve09v2_kzz7yh-f70880.xml
> +                  <lb ed="#V" n="26"/>Contra prius ordine nature est conuersio itellecius <!--should have t?-->
Yeah, I think it is supposed to be "intellectius," but there is clearly no "t."

2024-03-30 13:49 UTC, RobbieBuhite commented on kzz7yh-f70880/cod-ve09v2_kzz7yh-f70880.xml
> +      e<lb ed="#V" n="111" break="no"/>ceptionem speciet non est alia conuersio: nisi apprehensio: et
```suggestion
      <sic>e<lb ed="#V" n="111" break="no"/>ceptionem</sic> speciet non est alia conuersio: nisi apprehensio: et 
```

2024-03-30 13:49 UTC, RobbieBuhite commented on kzz7yh-f70880/cod-ve09v2_kzz7yh-f70880.xml
>        in<lb ed="#V" n="129" break="no"/>telligere sit agere. Et videtur quod sic: secundum philosophum
```suggestion
      in<lb ed="#V" n="129" break="no"/>telligere sit agere. Et videtur quod sic: secundum <ref>philosophum 
```

2024-03-30 13:49 UTC, RobbieBuhite commented on kzz7yh-f70880/cod-ve09v2_kzz7yh-f70880.xml
>        <lb ed="#V" n="130"/>primo ethicorum ca. 9. felicitas consistit in actu.
```suggestion
      <lb ed="#V" n="130"/>primo ethicorum ca. 9.</sic> felicitas consistit in actu. 
```

2024-03-30 13:49 UTC, RobbieBuhite commented on kzz7yh-f70880/cod-ve09v2_kzz7yh-f70880.xml
> +      <lb ed="#V" n="7"/>similitudinem: non tantum modo est passiuus: sed etiam
```suggestion
      <lb ed="#V" n="7"/>similitudinem: non tantummodo est passiuus: sed etiam 
```

2024-03-30 13:49 UTC, RobbieBuhite commented on kzz7yh-f70880/cod-ve09v2_kzz7yh-f70880.xml
> +      <lb ed="#V" n="7"/>similitudinem: non tantum modo est passiuus: sed etiam
These can be separate words, but often they get combined when they're next to each other.

2024-03-30 13:49 UTC, RobbieBuhite commented on kzz7yh-f70880/cod-ve09v2_kzz7yh-f70880.xml
> +               <head type="question-title">Utrum intellectus noster argumetando discurrens a creaturis ad creatorem</head>
```suggestion
               <head type="question-title">Utrum intellectus noster argumentando discurrens a creaturis ad creatorem in fine discursus intelligat per suam naturalem virtutem diuinam essentiam immediate</head>
```

2024-03-30 13:49 UTC, RobbieBuhite commented on kzz7yh-f70880/cod-ve09v2_kzz7yh-f70880.xml
> +                  <lb ed="#V" n="115"/>Respondeo quod quamuis homo bene vtendo <!--word-->
```suggestion
                  <lb ed="#V" n="115"/>Respondeo quod quamuis homo bene vtendo
```

2024-03-30 13:49 UTC, RobbieBuhite commented on kzz7yh-f70880/cod-ve09v2_kzz7yh-f70880.xml
> +                  <lb ed="#V" n="115"/>Respondeo quod quamuis homo bene vtendo <!--word-->
This is the gerund of the deponent verb, "utor."

2024-04-22 15:23 UTC, jeffreycwitt approved these changes

2024-04-22 15:23 UTC, merged