L2D25A3
scta-texts/kzz7yh pull request #247
Opened 2024-03-24 14:01 UTC by evyryan

Added question headers
Fixed fatheads
A few paragraphs that need to be added

2024-04-01 00:53 UTC, RobbieBuhite requested changes

2024-04-01 00:53 UTC, RobbieBuhite commented on kzz7yh-f75957/cod-ve09v2_kzz7yh-f75957.xml
> +      <lb ed="#V" n="66"/>cuius modi est ille qui ab ea immediate procedit: et hoc
```suggestion
      <lb ed="#V" n="66"/>cuiusmodi est ille qui ab ea immediate procedit: et hoc 
```

2024-04-01 00:53 UTC, RobbieBuhite commented on kzz7yh-f75957/cod-ve09v2_kzz7yh-f75957.xml
> +      <lb ed="#V" n="66"/>cuius modi est ille qui ab ea immediate procedit: et hoc
These are separate words that are often combined when next to each other.

2024-04-01 00:53 UTC, RobbieBuhite commented on kzz7yh-f75957/cod-ve09v2_kzz7yh-f75957.xml
> +      <lb ed="#V" n="100"/>SEcundo queritur vtrum omne ens<!--word--> sit
```suggestion
      <lb ed="#V" n="100"/>SEcundo queritur vtrum omne ens sit 
```

2024-04-01 00:53 UTC, RobbieBuhite commented on kzz7yh-f75957/cod-ve09v2_kzz7yh-f75957.xml
> +      <lb ed="#V" n="100"/>SEcundo queritur vtrum omne ens<!--word--> sit
ens, entis, n., "being, entity," related to ὠν, ὀντος in Greek.

2024-04-22 15:32 UTC, jeffreycwitt approved these changes

2024-04-22 15:33 UTC, merged