L2D28A2
scta-texts/kzz7yh pull request #273
Opened 2024-04-06 02:53 UTC by evyryan

Fixed fatheads
Added question headers
Two paragraphs need to be added

2024-04-10 21:09 UTC, RobbieBuhite requested changes

2024-04-10 21:09 UTC, RobbieBuhite commented on kzz7yh-f83454/cod-ve09v2_kzz7yh-f83454.xml
> +                  <lb ed="#V" n="55"/>Contra <ref>Aug. i. lib. retrac. cap. d<!--symbol?--></ref> voluntas ipsa nifi
```suggestion
                  <lb ed="#V" n="55"/>Contra <ref>Aug. i. lib. retrac. cap. 8</ref> voluntas ipsa nisi
```

2024-04-10 21:09 UTC, RobbieBuhite commented on kzz7yh-f83454/cod-ve09v2_kzz7yh-f83454.xml
> +                  <lb ed="#V" n="55"/>Contra <ref>Aug. i. lib. retrac. cap. d<!--symbol?--></ref> voluntas ipsa nifi
I think it's just an 8, but I am not totally sure.

2024-04-10 21:09 UTC, RobbieBuhite commented on kzz7yh-f83454/cod-ve09v2_kzz7yh-f83454.xml
> +               <head type="question-title">Utrum homo sine gratia gratum faciente possit aliwuam temptationem vincere</head>
```suggestion
               <head type="question-title">Utrum homo sine gratia gratum faciente possit aliquam temptationem vincere</head>
```

2024-07-25 11:48 UTC, jeffreycwitt approved these changes

2024-07-25 11:48 UTC, merged