L4D1A1
scta-texts/kzz7yh pull request #288
Opened 2024-04-12 18:25 UTC by evyryan

Fixed fatheads
Added question headers

2024-04-22 15:42 UTC, RobbieBuhite requested changes

2024-04-22 15:42 UTC, RobbieBuhite commented on kzz7yh-k87811/cod-ve09v4_kzz7yh-k87811.xml
> +      <lb ed="#V" n="17"/>habetur id est q id e.t<!--Sequence of Abbreviations--> Detrahe. Accedit verbum ad
```suggestion
      <lb ed="#V" n="17"/>habetur i. q. i. Detrahe.</ref> Accedit verbum ad 
```

2024-04-22 15:42 UTC, RobbieBuhite commented on kzz7yh-k87811/cod-ve09v4_kzz7yh-k87811.xml
> +                  <lb ed="#V" n="16"/>Contra <ref>Augu. homelia. 8. super Io.</ref> vltra medium et
```suggestion
                  <lb ed="#V" n="16"/>Contra <ref>Augu. homelia. 8. super Io. vltra medium et 
```

2024-04-22 15:42 UTC, RobbieBuhite commented on kzz7yh-k87811/cod-ve09v4_kzz7yh-k87811.xml
> +      ornan<lb ed="#V" n="19" break="no"/>do<!--Abbreviation--> actiue: ita sacramentum dicitur
```suggestion
      ornan<lb ed="#V" n="19" break="no"/>do actiue: ita sacramentum dicitur 
```

2024-04-22 15:42 UTC, RobbieBuhite commented on kzz7yh-k87811/cod-ve09v4_kzz7yh-k87811.xml
> +      conueni<lb ed="#V" n="122" break="no"/>ens et datur de sacramentis no. l.<!--Abbreviation--> et
```suggestion
      conueni<lb ed="#V" n="122" break="no"/>ens et datur de sacramentis numero l. et 
```

2024-07-29 22:09 UTC, jeffreycwitt approved these changes

2024-07-29 22:09 UTC, merged