L2D34A1
scta-texts/kzz7yh pull request #315
Opened 2024-04-25 19:20 UTC by evyryan

fixed fatheads
added question headers

2024-04-26 00:55 UTC, RobbieBuhite requested changes

2024-04-26 00:55 UTC, RobbieBuhite commented on kzz7yh-f98260/cod-ve09v2_kzz7yh-f98260.xml
> +      <ref>Dio<lb ed="#V" n="36" break="no"/>nysius</ref> intellexit malum non
```suggestion
      <ref>Dio<lb ed="#V" n="36" break="no"/>nysius</ref> intellexit malum non esse
```

2024-04-26 00:55 UTC, RobbieBuhite commented on kzz7yh-f98260/cod-ve09v2_kzz7yh-f98260.xml
> +      esse<lb ed="#V" n="37" break="no"/>in ente: sicut partem vel naturalem proprietatem
```suggestion
      <lb ed="#V" n="37" />in ente: sicut partem vel naturalem proprietatem 
```

2024-08-10 16:51 UTC, jeffreycwitt approved these changes

2024-08-10 16:51 UTC, merged